[package]
name = "maps-thingy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kmz2map"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
base64 = "0.22.1"
clap = { version = "4.6.5", features = ["derive"] }
quick-xml = "0.31.0"
zip = { version = "2", default-features = false, features = ["deflate"] }

[profile.release]
opt-level = 2
